fluxline_follow_controller:
  ros__parameters:
    angular_controller:
      kp: 0.7
      kd: 0.05
      target_value: 0.0
      angular_velocity_limit: 0.5
    linear_controller:
      kp: 0.6
      ki: 0.1
      kd: 0.3
      target_value: 0.0
      linear_velocity_limit: 0.5
